import pygame.image

health_bar_img = pygame.image.load("assets/healthBar.png")
console_left = pygame.image.load("assets/console_left_end.png")
console_right = pygame.image.load("assets/console_right_end.png")
console_mid = pygame.image.load("assets/hud_mid.png")
hud_right = pygame.image.load("assets/hud_right_end.png")
hud_left = pygame.image.load("assets/hud_left_end.png")
hud_mid = pygame.image.load("assets/hud_mid.png")
energy = pygame.image.load("assets/energy_pickup.png")
key = pygame.image.load("assets/key.png")
fire_icon = pygame.image.load("assets/fire_icon.png")
poison_icon = pygame.image.load("assets/poison_icon.png")
confusion_icon = pygame.image.load("assets/confusion_icon.png")
rock = pygame.image.load("assets/rock.png")
bat_1 = pygame.image.load("assets/bat-1.png")
bat_2 = pygame.image.load("assets/bat-2.png")
mushroom = pygame.image.load("assets/cave-mushrooms.png")
grass = pygame.image.load("assets/grass.png")
medkit = pygame.image.load("assets/medkit.png")
gargoyle = pygame.image.load("assets/gargoyle.png")
projectile = pygame.image.load("assets/projectile.png")
objects = pygame.image.load("assets/gfx/objects.png")
crate = pygame.image.load("assets/crate.png")
fire = pygame.image.load("assets/fire.png")
spikes = pygame.image.load("assets/spikes.png")
pressure_plate = pygame.image.load("assets/pressure_plate.png")
